database:
  path: data/database.db

server:
  host: "0.0.0.0"
  port: 8000
  reload: true

gigachat:
  certificate_path: "russian_trusted_root_ca_pem.crt"
  api_key: "INSERT_YOUR_KEY"
  model: "GigaChat-2-Max"
  max_tokens: 80000
  max_loop_cycles: 6